spring.application.name=visa-case-management-system
spring.docker.compose.lifecycle-management=start_only

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/visadatabase}
spring.datasource.username=${DB_USER:myuser}
spring.datasource.password=${DB_PASSWORD:secret}

# application.properties (default/test/prod)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.accessKey=${MINIO_ACCESS_KEY:admin}
minio.secretKey=${MINIO_SECRET_KEY:password}
minio.bucketName=${MINIO_BUCKET:visa-documents}
minio.region=${MINIO_REGION:eu-north-1}
minio.corsAllowedOrigins=${MINIO_CORS:http://localhost:8080}


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
